export const pct_Players = {
  // Male Players (Existing)
  "babar-azam": {
    name: "Babar Azam",
    age: 29,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 12902,
    highestScore: 158,
    PSLTeams: ["Karachi Kings", "Peshawar Zalmi"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 89.2,
    economy: 7.5,
    captain: true,
    totalCatches: 156,
    gender: "male"
  },
  "shaheen-afridi": {
    name: "Shaheen Afridi",
    age: 24,
    role: "Bowler",
    bowlingType: "Left-arm fast",
    battingType: "Left-handed",
    totalScore: 678,
    highestScore: 52,
    PSLTeams: ["Lahore Qalandars"],
    totalWickets: 253,
    highestWickets: 6,
    strikeRate: 85.1,
    economy: 8.2,
    captain: true,
    totalCatches: 42,
    gender: "male"
  },
  "mohammad-rizwan": {
    name: "Mohammad Rizwan",
    age: 31,
    role: "Wicketkeeper-Batsman",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 7895,
    highestScore: 115,
    PSLTeams: ["Karachi Kings", "Multan Sultans"],
    totalWickets: 2,
    highestWickets: 1,
    strikeRate: 88.6,
    economy: 8.0,
    captain: true,
    totalCatches: 218,
    gender: "male"
  },

  // Female Players (New Additions)
  "bismah-maroof": {
    name: "Bismah Maroof",
    age: 32,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 5680,
    highestScore: 124,
    PSLTeams: ["Women's Team A"],
    totalWickets: 45,
    highestWickets: 3,
    strikeRate: 86.4,
    economy: 6.8,
    captain: true,
    totalCatches: 89,
    gender: "female"
  },
  "nida-dar": {
    name: "Nida Dar",
    age: 36,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 3450,
    highestScore: 98,
    PSLTeams: ["Women's Team B"],
    totalWickets: 167,
    highestWickets: 5,
    strikeRate: 90.2,
    economy: 6.5,
    captain: true,
    totalCatches: 67,
    gender: "female"
  },
  "alya-riaz": {
    name: "Alya Riaz",
    age: 26,
    role: "All-rounder",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 1560,
    highestScore: 87,
    PSLTeams: ["Women's Team C"],
    totalWickets: 78,
    highestWickets: 4,
    strikeRate: 88.9,
    economy: 7.1,
    captain: false,
    totalCatches: 45,
    gender: "female"
  },
  "sadia-iqbal": {
    name: "Sadia Iqbal",
    age: 24,
    role: "Bowler",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 230,
    highestScore: 32,
    PSLTeams: ["Women's Team A"],
    totalWickets: 134,
    highestWickets: 5,
    strikeRate: 52.3,
    economy: 6.2,
    captain: false,
    totalCatches: 28,
    gender: "female"
  },
  "muneeba-ali": {
    name: "Muneeba Ali",
    age: 26,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Left-handed",
    totalScore: 1870,
    highestScore: 102,
    PSLTeams: ["Women's Team B"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 91.5,
    economy: 0,
    captain: false,
    totalCatches: 134,
    gender: "female"
  },
  "fatima-sana": {
    name: "Fatima Sana",
    age: 22,
    role: "All-rounder",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 890,
    highestScore: 65,
    PSLTeams: ["Women's Team C"],
    totalWickets: 98,
    highestWickets: 4,
    strikeRate: 76.8,
    economy: 7.3,
    captain: false,
    totalCatches: 32,
    gender: "female"
  },
  "diana-baig": {
    name: "Diana Baig",
    age: 28,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 345,
    highestScore: 41,
    PSLTeams: ["Women's Team A"],
    totalWickets: 156,
    highestWickets: 5,
    strikeRate: 48.9,
    economy: 6.9,
    captain: false,
    totalCatches: 41,
    gender: "female"
  },
  "nashra-sundhu": {
    name: "Nashra Sundhu",
    age: 25,
    role: "Bowler",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 128,
    highestScore: 22,
    PSLTeams: ["Women's Team B"],
    totalWickets: 112,
    highestWickets: 4,
    strikeRate: 45.6,
    economy: 6.4,
    captain: false,
    totalCatches: 19,
    gender: "female"
  },
  "oman-saeed": {
    name: "Oman Saeed",
    age: 29,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 2340,
    highestScore: 118,
    PSLTeams: ["Women's Team C"],
    totalWickets: 12,
    highestWickets: 2,
    strikeRate: 87.3,
    economy: 7.2,
    captain: false,
    totalCatches: 56,
    gender: "female"
  },
  "saba-nazir": {
    name: "Saba Nazir",
    age: 27,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 1890,
    highestScore: 96,
    PSLTeams: ["Women's Team A"],
    totalWickets: 8,
    highestWickets: 1,
    strikeRate: 84.7,
    economy: 7.0,
    captain: false,
    totalCatches: 48,
    gender: "female"
  },
  "anam-amin": {
    name: "Anam Amin",
    age: 31,
    role: "Bowler",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 210,
    highestScore: 28,
    PSLTeams: ["Women's Team B"],
    totalWickets: 178,
    highestWickets: 5,
    strikeRate: 43.2,
    economy: 6.1,
    captain: false,
    totalCatches: 24,
    gender: "female"
  },
  "kainat-imtiaz": {
    name: "Kainat Imtiaz",
    age: 30,
    role: "All-rounder",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 1120,
    highestScore: 74,
    PSLTeams: ["Women's Team C"],
    totalWickets: 67,
    highestWickets: 3,
    strikeRate: 79.8,
    economy: 7.4,
    captain: false,
    totalCatches: 37,
    gender: "female"
  },
  "sadia-yousuf": {
    name: "Sadia Yousuf",
    age: 23,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Left-handed",
    totalScore: 95,
    highestScore: 19,
    PSLTeams: ["Women's Team A"],
    totalWickets: 89,
    highestWickets: 4,
    strikeRate: 41.8,
    economy: 6.8,
    captain: false,
    totalCatches: 16,
    gender: "female"
  },
  "javeria-khan": {
    name: "Javeria Khan",
    age: 35,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 4560,
    highestScore: 133,
    PSLTeams: ["Women's Team B"],
    totalWickets: 34,
    highestWickets: 3,
    strikeRate: 83.2,
    economy: 6.9,
    captain: true,
    totalCatches: 78,
    gender: "female"
  },
  "nahida-khan": {
    name: "Nahida Khan",
    age: 36,
    role: "Batsman",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 2980,
    highestScore: 121,
    PSLTeams: ["Women's Team C"],
    totalWickets: 15,
    highestWickets: 2,
    strikeRate: 81.5,
    economy: 7.3,
    captain: false,
    totalCatches: 52,
    gender: "female"
  },
  "sana-mir": {
    name: "Sana Mir",
    age: 38,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 2340,
    highestScore: 89,
    PSLTeams: ["Women's Team A"],
    totalWickets: 245,
    highestWickets: 5,
    strikeRate: 75.6,
    economy: 6.3,
    captain: true,
    totalCatches: 67,
    gender: "female"
  },
  "waheeda-akhtar": {
    name: "Waheeda Akhtar",
    age: 21,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 78,
    highestScore: 16,
    PSLTeams: ["Women's Team B"],
    totalWickets: 56,
    highestWickets: 4,
    strikeRate: 39.4,
    economy: 7.1,
    captain: false,
    totalCatches: 12,
    gender: "female"
  },
  "mahnoor-kiran": {
    name: "Mahnoor Kiran",
    age: 19,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 670,
    highestScore: 88,
    PSLTeams: ["Women's Team C"],
    totalWickets: 5,
    highestWickets: 1,
    strikeRate: 89.3,
    economy: 7.5,
    captain: false,
    totalCatches: 29,
    gender: "female"
  },
  "rabiya-khan": {
    name: "Rabiya Khan",
    age: 24,
    role: "Bowler",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 112,
    highestScore: 24,
    PSLTeams: ["Women's Team A"],
    totalWickets: 102,
    highestWickets: 4,
    strikeRate: 46.7,
    economy: 6.6,
    captain: false,
    totalCatches: 21,
    gender: "female"
  },
  "zara-khan": {
    name: "Zara Khan",
    age: 22,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 890,
    highestScore: 76,
    PSLTeams: ["Women's Team B"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 82.4,
    economy: 0,
    captain: false,
    totalCatches: 98,
    gender: "female"
  },
  "hania-khan": {
    name: "Hania Khan",
    age: 25,
    role: "All-rounder",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 1340,
    highestScore: 92,
    PSLTeams: ["Women's Team C"],
    totalWickets: 45,
    highestWickets: 3,
    strikeRate: 85.1,
    economy: 7.2,
    captain: false,
    totalCatches: 41,
    gender: "female"
  },
  "sara-fatima": {
    name: "Sara Fatima",
    age: 27,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Left-handed",
    totalScore: 1870,
    highestScore: 104,
    PSLTeams: ["Women's Team A"],
    totalWickets: 9,
    highestWickets: 2,
    strikeRate: 86.9,
    economy: 7.0,
    captain: false,
    totalCatches: 47,
    gender: "female"
  },
  "mehwish-zafar": {
    name: "Mehwish Zafar",
    age: 26,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 156,
    highestScore: 29,
    PSLTeams: ["Women's Team B"],
    totalWickets: 78,
    highestWickets: 4,
    strikeRate: 51.2,
    economy: 7.3,
    captain: false,
    totalCatches: 18,
    gender: "female"
  },
  "zunaira-shah": {
    name: "Zunaira Shah",
    age: 20,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 540,
    highestScore: 67,
    PSLTeams: ["Women's Team C"],
    totalWickets: 34,
    highestWickets: 3,
    strikeRate: 78.9,
    economy: 6.8,
    captain: false,
    totalCatches: 26,
    gender: "female"
  },
  "ayesha-naseem": {
    name: "Ayesha Naseem",
    age: 19,
    role: "Batsman",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 780,
    highestScore: 95,
    PSLTeams: ["Women's Team A"],
    totalWickets: 6,
    highestWickets: 1,
    strikeRate: 92.1,
    economy: 7.4,
    captain: false,
    totalCatches: 34,
    gender: "female"
  },
  "tuba-hassan": {
    name: "Tuba Hassan",
    age: 23,
    role: "Bowler",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 89,
    highestScore: 21,
    PSLTeams: ["Women's Team B"],
    totalWickets: 67,
    highestWickets: 4,
    strikeRate: 44.5,
    economy: 6.7,
    captain: false,
    totalCatches: 15,
    gender: "female"
  },
  "areesha-noor": {
    name: "Areesha Noor",
    age: 21,
    role: "All-rounder",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 690,
    highestScore: 78,
    PSLTeams: ["Women's Team C"],
    totalWickets: 41,
    highestWickets: 3,
    strikeRate: 83.7,
    economy: 6.9,
    captain: false,
    totalCatches: 31,
    gender: "female"
  },
  "laiba-nasir": {
    name: "Laiba Nasir",
    age: 22,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 1020,
    highestScore: 89,
    PSLTeams: ["Women's Team A"],
    totalWickets: 7,
    highestWickets: 1,
    strikeRate: 87.2,
    economy: 7.1,
    captain: false,
    totalCatches: 39,
    gender: "female"
  },
  "qurat-ul-ain": {
    name: "Qurat ul Ain",
    age: 28,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 1450,
    highestScore: 83,
    PSLTeams: ["Women's Team B"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 84.6,
    economy: 0,
    captain: false,
    totalCatches: 112,
    gender: "female"
  },
  "saima-malik": {
    name: "Saima Malik",
    age: 29,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 134,
    highestScore: 26,
    PSLTeams: ["Women's Team C"],
    totalWickets: 91,
    highestWickets: 5,
    strikeRate: 47.8,
    economy: 7.0,
    captain: false,
    totalCatches: 22,
    gender: "female"
  },
  "zoya-khan": {
    name: "Zoya Khan",
    age: 24,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 890,
    highestScore: 71,
    PSLTeams: ["Women's Team A"],
    totalWickets: 52,
    highestWickets: 4,
    strikeRate: 81.3,
    economy: 6.8,
    captain: false,
    totalCatches: 35,
    gender: "female"
  },
  "mehak-kiran": {
    name: "Mehak Kiran",
    age: 20,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Left-handed",
    totalScore: 560,
    highestScore: 82,
    PSLTeams: ["Women's Team B"],
    totalWickets: 4,
    highestWickets: 1,
    strikeRate: 88.4,
    economy: 7.3,
    captain: false,
    totalCatches: 27,
    gender: "female"
  },
  "amina-khan": {
    name: "Amina Khan",
    age: 26,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Left-handed",
    totalScore: 98,
    highestScore: 23,
    PSLTeams: ["Women's Team C"],
    totalWickets: 83,
    highestWickets: 4,
    strikeRate: 43.2,
    economy: 6.9,
    captain: false,
    totalCatches: 19,
    gender: "female"
  },
  "sahar-zaman": {
    name: "Sahar Zaman",
    age: 25,
    role: "All-rounder",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 1120,
    highestScore: 94,
    PSLTeams: ["Women's Team A"],
    totalWickets: 38,
    highestWickets: 3,
    strikeRate: 85.7,
    economy: 7.1,
    captain: false,
    totalCatches: 42,
    gender: "female"
  },
  "fariha-rasheed": {
    name: "Fariha Rasheed",
    age: 23,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 780,
    highestScore: 79,
    PSLTeams: ["Women's Team B"],
    totalWickets: 8,
    highestWickets: 2,
    strikeRate: 83.9,
    economy: 7.0,
    captain: false,
    totalCatches: 33,
    gender: "female"
  },
  "nadia-khan": {
    name: "Nadia Khan",
    age: 27,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 1340,
    highestScore: 87,
    PSLTeams: ["Women's Team C"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 86.2,
    economy: 0,
    captain: false,
    totalCatches: 106,
    gender: "female"
  },
  "sana-khan": {
    name: "Sana Khan",
    age: 24,
    role: "Bowler",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 67,
    highestScore: 18,
    PSLTeams: ["Women's Team A"],
    totalWickets: 74,
    highestWickets: 4,
    strikeRate: 42.8,
    economy: 6.5,
    captain: false,
    totalCatches: 14,
    gender: "female"
  },
  "zainab-abbas": {
    name: "Zainab Abbas",
    age: 22,
    role: "All-rounder",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 920,
    highestScore: 85,
    PSLTeams: ["Women's Team B"],
    totalWickets: 46,
    highestWickets: 3,
    strikeRate: 84.1,
    economy: 6.7,
    captain: false,
    totalCatches: 38,
    gender: "female"
  },
  "mehwish-khan": {
    name: "Mehwish Khan",
    age: 25,
    role: "Batsman",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 1560,
    highestScore: 108,
    PSLTeams: ["Women's Team C"],
    totalWickets: 11,
    highestWickets: 2,
    strikeRate: 87.8,
    economy: 7.2,
    captain: false,
    totalCatches: 44,
    gender: "female"
  },
  "rabia-shah": {
    name: "Rabia Shah",
    age: 26,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 112,
    highestScore: 25,
    PSLTeams: ["Women's Team A"],
    totalWickets: 89,
    highestWickets: 5,
    strikeRate: 48.3,
    economy: 7.1,
    captain: false,
    totalCatches: 21,
    gender: "female"
  },
  "sadia-khan": {
    name: "Sadia Khan",
    age: 23,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 670,
    highestScore: 72,
    PSLTeams: ["Women's Team B"],
    totalWickets: 39,
    highestWickets: 3,
    strikeRate: 79.5,
    economy: 6.9,
    captain: false,
    totalCatches: 29,
    gender: "female"
  },
  "zara-ahmed": {
    name: "Zara Ahmed",
    age: 21,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 890,
    highestScore: 91,
    PSLTeams: ["Women's Team C"],
    totalWickets: 6,
    highestWickets: 1,
    strikeRate: 88.7,
    economy: 7.3,
    captain: false,
    totalCatches: 36,
    gender: "female"
  },
  "hina-khan": {
    name: "Hina Khan",
    age: 28,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Left-handed",
    totalScore: 145,
    highestScore: 31,
    PSLTeams: ["Women's Team A"],
    totalWickets: 96,
    highestWickets: 5,
    strikeRate: 49.2,
    economy: 6.8,
    captain: false,
    totalCatches: 23,
    gender: "female"
  },
  "sara-khan": {
    name: "Sara Khan",
    age: 24,
    role: "All-rounder",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 780,
    highestScore: 68,
    PSLTeams: ["Women's Team B"],
    totalWickets: 43,
    highestWickets: 3,
    strikeRate: 82.6,
    economy: 7.0,
    captain: false,
    totalCatches: 34,
    gender: "female"
  },
  "ayesha-khan": {
    name: "Ayesha Khan",
    age: 22,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 1020,
    highestScore: 96,
    PSLTeams: ["Women's Team C"],
    totalWickets: 9,
    highestWickets: 2,
    strikeRate: 86.9,
    economy: 7.1,
    captain: false,
    totalCatches: 41,
    gender: "female"
  }
};