export const pct_Players = {
  "Babar-Azam": {
    name: "Babar Azam",
    age: 29,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 12902,
    highestScore: 158,
    PSLTeams: ["Karachi Kings", "Peshawar Zalmi"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 89.2,
    economy: 7.5
  },
  "Shaheen-Afridi": {
    name: "Shaheen Afridi",
    age: 24,
    role: "Bowler",
    bowlingType: "Left-arm fast",
    battingType: "Left-handed",
    totalScore: 678,
    highestScore: 52,
    PSLTeams: ["Lahore Qalandars"],
    totalWickets: 253,
    highestWickets: 6,
    strikeRate: 85.1,
    economy: 8.2
  },
  "Mohammad-Rizwan": {
    name: "Mohammad Rizwan",
    age: 31,
    role: "Wicketkeeper-Batsman",
    bowlingType: "Right-arm medium",
    battingType: "Right-handed",
    totalScore: 7895,
    highestScore: 115,
    PSLTeams: ["Karachi Kings", "Multan Sultans"],
    totalWickets: 2,
    highestWickets: 1,
    strikeRate: 88.6,
    economy: 8.0
  },
  "Shadab-Khan": {
    name: "Shadab Khan",
    age: 25,
    role: "All-rounder",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 2105,
    highestScore: 86,
    PSLTeams: ["Islamabad United"],
    totalWickets: 219,
    highestWickets: 5,
    strikeRate: 91.3,
    economy: 7.2
  },
  "Fakhar-Zaman": {
    name: "Fakhar Zaman",
    age: 33,
    role: "Batsman",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 5872,
    highestScore: 210,
    PSLTeams: ["Lahore Qalandars"],
    totalWickets: 12,
    highestWickets: 2,
    strikeRate: 94.5,
    economy: 7.8
  },
  "Haris-Rauf": {
    name: "Haris Rauf",
    age: 30,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 156,
    highestScore: 24,
    PSLTeams: ["Lahore Qalandars"],
    totalWickets: 187,
    highestWickets: 5,
    strikeRate: 65.2,
    economy: 8.9
  },
  "Imad-Wasim": {
    name: "Imad Wasim",
    age: 35,
    role: "All-rounder",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 3250,
    highestScore: 63,
    PSLTeams: ["Karachi Kings", "Islamabad United"],
    totalWickets: 165,
    highestWickets: 4,
    strikeRate: 87.4,
    economy: 6.9
  },
  "Mohammad-Hafeez": {
    name: "Mohammad Hafeez",
    age: 43,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 12789,
    highestScore: 140,
    PSLTeams: ["Peshawar Zalmi", "Lahore Qalandars", "Karachi Kings"],
    totalWickets: 246,
    highestWickets: 4,
    strikeRate: 85.9,
    economy: 7.1
  },
  "Hasan-Ali": {
    name: "Hasan Ali",
    age: 29,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 489,
    highestScore: 59,
    PSLTeams: ["Peshawar Zalmi", "Islamabad United", "Karachi Kings"],
    totalWickets: 229,
    highestWickets: 5,
    strikeRate: 70.1,
    economy: 8.3
  },
  "Sarfaraz-Ahmed": {
    name: "Sarfaraz Ahmed",
    age: 37,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 6875,
    highestScore: 118,
    PSLTeams: ["Quetta Gladiators", "Peshawar Zalmi"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 83.2,
    economy: 0
  },
  "Naseem-Shah": {
    name: "Naseem Shah",
    age: 21,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 128,
    highestScore: 25,
    PSLTeams: ["Quetta Gladiators", "Islamabad United"],
    totalWickets: 89,
    highestWickets: 5,
    strikeRate: 55.6,
    economy: 7.8
  },
  "Iftikhar-Ahmed": {
    name: "Iftikhar Ahmed",
    age: 33,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 2150,
    highestScore: 102,
    PSLTeams: ["Karachi Kings", "Peshawar Zalmi", "Quetta Gladiators"],
    totalWickets: 45,
    highestWickets: 3,
    strikeRate: 89.7,
    economy: 7.4
  },
  "Mohammad-Nawaz": {
    name: "Mohammad Nawaz",
    age: 30,
    role: "All-rounder",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 1250,
    highestScore: 61,
    PSLTeams: ["Quetta Gladiators", "Peshawar Zalmi"],
    totalWickets: 132,
    highestWickets: 4,
    strikeRate: 86.3,
    economy: 7.1
  },
  "Abrar-Ahmed": {
    name: "Abrar Ahmed",
    age: 25,
    role: "Bowler",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 56,
    highestScore: 14,
    PSLTeams: ["Karachi Kings", "Islamabad United"],
    totalWickets: 47,
    highestWickets: 7,
    strikeRate: 42.1,
    economy: 6.9
  },
  "Azam-Khan": {
    name: "Azam Khan",
    age: 25,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 890,
    highestScore: 97,
    PSLTeams: ["Quetta Gladiators", "Islamabad United"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 95.3,
    economy: 0
  },
  "Mohammad-Amir": {
    name: "Mohammad Amir",
    age: 32,
    role: "Bowler",
    bowlingType: "Left-arm fast",
    battingType: "Left-handed",
    totalScore: 645,
    highestScore: 73,
    PSLTeams: ["Karachi Kings", "Quetta Gladiators"],
    totalWickets: 259,
    highestWickets: 6,
    strikeRate: 68.2,
    economy: 7.8
  },
  "Saim-Ayub": {
    name: "Saim Ayub",
    age: 21,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Left-handed",
    totalScore: 856,
    highestScore: 109,
    PSLTeams: ["Peshawar Zalmi"],
    totalWickets: 8,
    highestWickets: 2,
    strikeRate: 92.1,
    economy: 7.5
  },
  "Abdullah-Shafique": {
    name: "Abdullah Shafique",
    age: 24,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 1450,
    highestScore: 160,
    PSLTeams: ["Lahore Qalandars"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 86.7,
    economy: 8.0
  },
  "Salman-Ali-Agha": {
    name: "Salman Ali Agha",
    age: 30,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 1780,
    highestScore: 132,
    PSLTeams: ["Peshawar Zalmi", "Islamabad United"],
    totalWickets: 28,
    highestWickets: 3,
    strikeRate: 84.5,
    economy: 7.2
  },
  "Mohammad-Wasim-Jr": {
    name: "Mohammad Wasim Jr",
    age: 22,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 195,
    highestScore: 31,
    PSLTeams: ["Islamabad United"],
    totalWickets: 67,
    highestWickets: 4,
    strikeRate: 58.9,
    economy: 8.4
  },
  "Agha-Salman": {
    name: "Agha Salman",
    age: 30,
    role: "All-rounder",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 1560,
    highestScore: 118,
    PSLTeams: ["Karachi Kings", "Multan Sultans"],
    totalWickets: 32,
    highestWickets: 3,
    strikeRate: 83.2,
    economy: 7.1
  },
  "Khushdil-Shah": {
    name: "Khushdil Shah",
    age: 29,
    role: "All-rounder",
    bowlingType: "Slow left-arm orthodox",
    battingType: "Left-handed",
    totalScore: 980,
    highestScore: 106,
    PSLTeams: ["Multan Sultans"],
    totalWickets: 24,
    highestWickets: 2,
    strikeRate: 88.9,
    economy: 7.6
  },
  "Usman-Qadir": {
    name: "Usman Qadir",
    age: 31,
    role: "Bowler",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 87,
    highestScore: 18,
    PSLTeams: ["Lahore Qalandars", "Multan Sultans"],
    totalWickets: 89,
    highestWickets: 4,
    strikeRate: 45.6,
    economy: 7.9
  },
  "Zaman-Khan": {
    name: "Zaman Khan",
    age: 22,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 42,
    highestScore: 12,
    PSLTeams: ["Lahore Qalandars"],
    totalWickets: 54,
    highestWickets: 4,
    strikeRate: 38.7,
    economy: 8.7
  },
  "Shan-Masood": {
    name: "Shan Masood",
    age: 34,
    role: "Batsman",
    bowlingType: "Right-arm medium",
    battingType: "Left-handed",
    totalScore: 4560,
    highestScore: 156,
    PSLTeams: ["Karachi Kings", "Multan Sultans"],
    totalWickets: 5,
    highestWickets: 1,
    strikeRate: 82.3,
    economy: 7.8
  },
  "Imam-ul-Haq": {
    name: "Imam-ul-Haq",
    age: 28,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Left-handed",
    totalScore: 5780,
    highestScore: 151,
    PSLTeams: ["Peshawar Zalmi"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 81.5,
    economy: 7.2
  },
  "Faheem-Ashraf": {
    name: "Faheem Ashraf",
    age: 30,
    role: "All-rounder",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 1560,
    highestScore: 91,
    PSLTeams: ["Islamabad United", "Peshawar Zalmi"],
    totalWickets: 145,
    highestWickets: 5,
    strikeRate: 79.8,
    economy: 8.1
  },
  "Mohammad-Haris": {
    name: "Mohammad Haris",
    age: 23,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 680,
    highestScore: 85,
    PSLTeams: ["Peshawar Zalmi"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 93.4,
    economy: 7.5
  },
  "Aamer-Jamal": {
    name: "Aamer Jamal",
    age: 27,
    role: "All-rounder",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 420,
    highestScore: 56,
    PSLTeams: ["Islamabad United"],
    totalWickets: 38,
    highestWickets: 3,
    strikeRate: 72.3,
    economy: 8.3
  },
  "Tayyab-Tahir": {
    name: "Tayyab Tahir",
    age: 30,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 890,
    highestScore: 108,
    PSLTeams: ["Karachi Kings"],
    totalWickets: 6,
    highestWickets: 1,
    strikeRate: 87.6,
    economy: 7.4
  },
  "Mir-Hamza": {
    name: "Mir Hamza",
    age: 31,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Left-handed",
    totalScore: 125,
    highestScore: 28,
    PSLTeams: ["Karachi Kings"],
    totalWickets: 156,
    highestWickets: 6,
    strikeRate: 52.1,
    economy: 7.9
  },
  "Shahnawaz-Dahani": {
    name: "Shahnawaz Dahani",
    age: 25,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 68,
    highestScore: 16,
    PSLTeams: ["Multan Sultans"],
    totalWickets: 72,
    highestWickets: 4,
    strikeRate: 48.9,
    economy: 8.6
  },
  "Kamran-Ghulam": {
    name: "Kamran Ghulam",
    age: 28,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 2340,
    highestScore: 166,
    PSLTeams: ["Peshawar Zalmi"],
    totalWickets: 12,
    highestWickets: 2,
    strikeRate: 83.9,
    economy: 7.3
  },
  "Rohail-Nazir": {
    name: "Rohail Nazir",
    age: 22,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 560,
    highestScore: 77,
    PSLTeams: ["Islamabad United"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 81.2,
    economy: 0
  },
  "Haider-Ali": {
    name: "Haider Ali",
    age: 23,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 980,
    highestScore: 91,
    PSLTeams: ["Peshawar Zalmi", "Islamabad United"],
    totalWickets: 3,
    highestWickets: 1,
    strikeRate: 89.7,
    economy: 7.8
  },
  "Mohammad-Ali": {
    name: "Mohammad Ali",
    age: 26,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 45,
    highestScore: 11,
    PSLTeams: ["Multan Sultans"],
    totalWickets: 63,
    highestWickets: 4,
    strikeRate: 41.2,
    economy: 8.2
  },
  "Arshad-Iqbal": {
    name: "Arshad Iqbal",
    age: 23,
    role: "Bowler",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 32,
    highestScore: 9,
    PSLTeams: ["Peshawar Zalmi"],
    totalWickets: 48,
    highestWickets: 3,
    strikeRate: 38.5,
    economy: 8.5
  },
  "Hussain-Talat": {
    name: "Hussain Talat",
    age: 27,
    role: "All-rounder",
    bowlingType: "Right-arm medium",
    battingType: "Left-handed",
    totalScore: 1340,
    highestScore: 116,
    PSLTeams: ["Islamabad United", "Karachi Kings"],
    totalWickets: 42,
    highestWickets: 3,
    strikeRate: 85.6,
    economy: 8.0
  },
  "Asif-Ali": {
    name: "Asif Ali",
    age: 32,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 2450,
    highestScore: 101,
    PSLTeams: ["Islamabad United", "Peshawar Zalmi"],
    totalWickets: 8,
    highestWickets: 2,
    strikeRate: 96.8,
    economy: 7.9
  },
  "Umaid-Asif": {
    name: "Umaid Asif",
    age: 40,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 320,
    highestScore: 45,
    PSLTeams: ["Karachi Kings", "Quetta Gladiators"],
    totalWickets: 198,
    highestWickets: 5,
    strikeRate: 62.3,
    economy: 8.4
  },
  "Amad-Butt": {
    name: "Amad Butt",
    age: 28,
    role: "All-rounder",
    bowlingType: "Right-arm fast",
    battingType: "Right-handed",
    totalScore: 580,
    highestScore: 54,
    PSLTeams: ["Peshawar Zalmi", "Quetta Gladiators"],
    totalWickets: 76,
    highestWickets: 4,
    strikeRate: 71.5,
    economy: 8.7
  },
  "Akif-Javed": {
    name: "Akif Javed",
    age: 23,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Left-handed",
    totalScore: 28,
    highestScore: 8,
    PSLTeams: ["Quetta Gladiators"],
    totalWickets: 41,
    highestWickets: 3,
    strikeRate: 39.8,
    economy: 8.3
  },
  "Mohammad-Ilyas": {
    name: "Mohammad Ilyas",
    age: 24,
    role: "Bowler",
    bowlingType: "Right-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 52,
    highestScore: 14,
    PSLTeams: ["Multan Sultans", "Quetta Gladiators"],
    totalWickets: 58,
    highestWickets: 4,
    strikeRate: 44.6,
    economy: 8.1
  },
  "Ali-Imran": {
    name: "Ali Imran",
    age: 25,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Right-handed",
    totalScore: 720,
    highestScore: 89,
    PSLTeams: ["Islamabad United"],
    totalWickets: 7,
    highestWickets: 1,
    strikeRate: 86.4,
    economy: 7.6
  },
  "Mohammad-Akhlaq": {
    name: "Mohammad Akhlaq",
    age: 31,
    role: "Wicketkeeper-Batsman",
    bowlingType: "N/A",
    battingType: "Right-handed",
    totalScore: 980,
    highestScore: 112,
    PSLTeams: ["Quetta Gladiators"],
    totalWickets: 0,
    highestWickets: 0,
    strikeRate: 82.7,
    economy: 0
  },
  "Rumman-Raees": {
    name: "Rumman Raees",
    age: 32,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Right-handed",
    totalScore: 95,
    highestScore: 22,
    PSLTeams: ["Karachi Kings", "Islamabad United"],
    totalWickets: 134,
    highestWickets: 4,
    strikeRate: 51.3,
    economy: 7.7
  },
  "Sohail-Tanvir": {
    name: "Sohail Tanvir",
    age: 39,
    role: "Bowler",
    bowlingType: "Left-arm fast-medium",
    battingType: "Left-handed",
    totalScore: 980,
    highestScore: 73,
    PSLTeams: ["Quetta Gladiators", "Multan Sultans"],
    totalWickets: 289,
    highestWickets: 6,
    strikeRate: 67.8,
    economy: 7.4
  },
  "Wahab-Riaz": {
    name: "Wahab Riaz",
    age: 38,
    role: "Bowler",
    bowlingType: "Left-arm fast",
    battingType: "Right-handed",
    totalScore: 1250,
    highestScore: 54,
    PSLTeams: ["Peshawar Zalmi", "Karachi Kings"],
    totalWickets: 312,
    highestWickets: 5,
    strikeRate: 63.4,
    economy: 8.2
  },
  "Ahmed-Shehzad": {
    name: "Ahmed Shehzad",
    age: 32,
    role: "Batsman",
    bowlingType: "Right-arm leg break",
    battingType: "Right-handed",
    totalScore: 6780,
    highestScore: 147,
    PSLTeams: ["Quetta Gladiators", "Multan Sultans"],
    totalWickets: 15,
    highestWickets: 2,
    strikeRate: 84.3,
    economy: 7.8
  },
  "Sharjeel-Khan": {
    name: "Sharjeel Khan",
    age: 34,
    role: "Batsman",
    bowlingType: "Right-arm off break",
    battingType: "Left-handed",
    totalScore: 4560,
    highestScore: 152,
    PSLTeams: ["Karachi Kings", "Islamabad United"],
    totalWickets: 8,
    highestWickets: 1,
    strikeRate: 93.7,
    economy: 7.9
  }
};